openapi: 3.2.0
info:
  version: '1.0'
  title: Remittance Endpoints API
  description: The Remittance API allows you to create tax remittance transactions.
  contact:
    name: API Support
    email: help@vopay.com
servers:
- url: https://earthnode-dev.vopay.com/api/v2
tags:
- name: Remittance Endpoints
paths:
  /remittance/create:
    post:
      description: This endpoint is used to create a tax remittance transaction.
      summary: remittance/create
      tags:
      - Remittance Endpoints
      operationId: RemittanceCreatePost
      deprecated: false
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                AccountID:
                  description: Your account ID
                  type: string
                Key:
                  description: API key for the account
                  type: string
                Signature:
                  description: Hashed signature for the request
                  type: string
                ClientAccountID:
                  description: Client Account ID
                  type: string
                IdempotencyKey:
                  description: A unique key which the server can use to recognize and reject subsequent retries of the same request.
                  type: string
                TaxRemittanceType:
                  description: 'The type of tax remittance to perform. Valid options: FED_PAYROLL_THRESHOLD_1, FED_PAYROLL_THRESHOLD_2, FED_PAYROLL_REGULAR_OR_QUARTERLY, FED_CORPORATE_TAX, FED_GST_HST_RETURN, ON_EMPLOYER_HEALTH_TAX, QC_PAYROLL_TWICE_MONTHLY, QC_PAYROLL_WEEKLY, QC_PAYROLL_MONTHLY, QC_GST_HST_QST_COMBINED_RETURN, QC_CORP_INCOME_TAX_REMITTANCE, QC_SUPPORT_PAYMENTS_COLLECTION, QC_PAYROLL_QUARTERLY, ON_FAMILY_RESPONSIBILITY_OFFICE, or WCB_NOVA_SCOTIA_PREMIUM.'
                  type: string
                Amount:
                  description: The total amount of the remittance payment.
                  type: number
                TaxAccountNumber:
                  description: The tax account number for the remittance.
                  type: string
                TaxPeriodEndDate:
                  description: The end date of the tax period (YYYY-MM-DD).
                  type: string
                PayerName:
                  description: The legal name of the payer.
                  type: string
                ClientReferenceNumber:
                  description: An optional reference number which was associated with the transaction.
                  type: string
                Notes:
                  description: An optional note to associate with the transaction.
                  type: string
                Details:
                  description: A JSON formatted string specifying additional data that is required for certain remittance types. Please contact your integration specialist for specifics.
                  type: string
                GLCode:
                  description: An optional unique identification general ledger code.
                  type: string
              required:
              - AccountID
              - Key
              - Signature
              - TaxRemittanceType
              - Amount
              - TaxAccountNumber
              - PayerName
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  Success:
                    type: boolean
                    description: True if the request was successful, false if it failed
                    example: 'true'
                  ErrorMessage:
                    type: string
                    description: Contains a description of the error if the request failed
                    example: ''
                  TransactionID:
                    type: string
                    description: The unique ID of the transaction that was just performed. This ID should be saved as it is required in order to look up status information on the transaction.
                    example: '1234567'
